{
 "title": "Confluent Oracle CDC",
 "description": "Monitor Confluent Oracle CDC connector",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } },
   {
    "name": "kafka_connect_cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(kafka_connect_cluster_id)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"kafka-connect\", env=\"$env\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"},instance)"
    }
   },
   {
    "name": "connector",
    "label": "Connector name",
    "query": {
     "query": "label_values({job=\"kafka-connect\", env=\"$env\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"},connector)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Oracle CDC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Streaming Lag From Source",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_oracle_cdc_source_task_metrics_context_streaming_Number{client_type=\"connect.oracle.cdc\", connector=~\"$connector\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\", env=~\"$env\", instance=~\"$instance\", job=\"kafka-connect\", name=\"streaming-lag-from-source-in-milliseconds\"}",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Streaming Lag From Source",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_oracle_cdc_source_task_metrics_context_streaming_Number{client_type=\"connect.oracle.cdc\", connector=~\"$connector\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\", env=~\"$env\", instance=~\"$instance\", job=\"kafka-connect\", name=\"streaming-lag-from-source-in-milliseconds\"}",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "current-scn - offset-scn",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_oracle_cdc_source_task_metrics_context_streaming_Number{client_type=\"connect.oracle.cdc\", connector=~\"$connector\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\", env=~\"$env\", instance=~\"$instance\", job=\"kafka-connect\", name=\"offset-scn\"}) by (connector) - sum(kafka_connect_oracle_cdc_source_task_metrics_context_streaming_Number{client_type=\"connect.oracle.cdc\", connector=~\"$connector\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\", env=~\"$env\", instance=~\"$instance\", job=\"kafka-connect\", name=\"current-scn\"}) by (connector)",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "current-scn - offset-scn",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_connect_oracle_cdc_source_task_metrics_context_streaming_Number{client_type=\"connect.oracle.cdc\", connector=~\"$connector\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\", env=~\"$env\", instance=~\"$instance\", job=\"kafka-connect\", name=\"offset-scn\"}) by (connector) - sum(kafka_connect_oracle_cdc_source_task_metrics_context_streaming_Number{client_type=\"connect.oracle.cdc\", connector=~\"$connector\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\", env=~\"$env\", instance=~\"$instance\", job=\"kafka-connect\", name=\"current-scn\"}) by (connector)",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Count of redo log files in log miner session",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_oracle_cdc_source_task_metrics_context_streaming_Number{client_type=\"connect.oracle.cdc\", connector=~\"$connector\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\", env=~\"$env\", instance=~\"$instance\", job=\"kafka-connect\", name=\"logmining-session-redo-log-files-count\"}",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Count of redo log files in log miner session",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_oracle_cdc_source_task_metrics_context_streaming_Number{client_type=\"connect.oracle.cdc\", connector=~\"$connector\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\", env=~\"$env\", instance=~\"$instance\", job=\"kafka-connect\", name=\"logmining-session-redo-log-files-count\"}",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Current Log Mining Range (mining_end_scn - mining_start_scn)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_oracle_cdc_source_task_metrics_context_streaming_Number{client_type=\"connect.oracle.cdc\", connector=~\"$connector\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\", env=~\"$env\", instance=~\"$instance\", job=\"kafka-connect\", name=\"logmining-session-end-scn\"}) by (connector) - sum(kafka_connect_oracle_cdc_source_task_metrics_context_streaming_Number{client_type=\"connect.oracle.cdc\", connector=~\"$connector\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\", env=~\"$env\", instance=~\"$instance\", job=\"kafka-connect\", name=\"logmining-session-start-scn\"}) by (connector)",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Log Mining Range (mining_end_scn - mining_start_scn)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_connect_oracle_cdc_source_task_metrics_context_streaming_Number{client_type=\"connect.oracle.cdc\", connector=~\"$connector\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\", env=~\"$env\", instance=~\"$instance\", job=\"kafka-connect\", name=\"logmining-session-end-scn\"}) by (connector) - sum(kafka_connect_oracle_cdc_source_task_metrics_context_streaming_Number{client_type=\"connect.oracle.cdc\", connector=~\"$connector\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\", env=~\"$env\", instance=~\"$instance\", job=\"kafka-connect\", name=\"logmining-session-start-scn\"}) by (connector)",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Active Transactions in Buffer",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_oracle_cdc_source_task_metrics_context_streaming_Number{client_type=\"connect.oracle.cdc\", connector=~\"$connector\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\", env=~\"$env\", instance=~\"$instance\", job=\"kafka-connect\", name=\"count-active-transactions-in-buffer\"}",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Current Age of Oldest Transaction in Buffer",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_oracle_cdc_source_task_metrics_context_streaming_Number{client_type=\"connect.oracle.cdc\", connector=~\"$connector\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\", env=~\"$env\", instance=~\"$instance\", job=\"kafka-connect\", name=\"age-of-oldest-transaction-in-buffer-in-milliseconds\"}",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Processed Transactions in Cache",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_oracle_cdc_source_task_metrics_context_streaming_Number{client_type=\"connect.oracle.cdc\", connector=~\"$connector\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\", env=~\"$env\", instance=~\"$instance\", job=\"kafka-connect\", name=\"count-processed-transactions-in-cache\"}",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Age of Oldest Transaction in Buffer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_oracle_cdc_source_task_metrics_context_streaming_Number{client_type=\"connect.oracle.cdc\", connector=~\"$connector\", kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\", env=~\"$env\", instance=~\"$instance\", job=\"kafka-connect\", name=\"age-of-oldest-transaction-in-buffer-in-milliseconds\"}",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka-connect\",env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",instance=~\"$instance\"}[5m])",
     "legendFormat": "{{kafka_connect_cluster_id}}-{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_used_bytes{job=\"kafka-connect\",env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",instance=~\"$instance\"})",
     "legendFormat": "{{kafka_connect_cluster_id}}-{{instance}}"
    },
    {
     "expr": "jvm_memory_max_bytes{job=\"kafka-connect\",env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",instance=~\"$instance\",area=\"heap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM GC time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka-connect\",env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{kafka_connect_cluster_id}}-{{instance}}"
    }
   ]
  }
 ]
}