ALTER SESSION SET CONTAINER=CDB$ROOT;
CREATE ROLE C##CDC_PRIVS;
CREATE USER C##MYUSER IDENTIFIED BY confluent123 CONTAINER=ALL;
ALTER USER C##MYUSER QUOTA UNLIMITED ON USERS;
ALTER USER C##MYUSER SET CONTAINER_DATA = (CDB$ROOT, XEPDB1) CONTAINER=CURRENT;
GRANT C##CDC_PRIVS to C##MYUSER CONTAINER=ALL;

GRANT CONNECT TO C##CDC_PRIVS CONTAINER=ALL;
GRANT CREATE SESSION TO C##CDC_PRIVS CONTAINER=ALL;
GRANT LOGMINING TO C##CDC_PRIVS CONTAINER=ALL;

GRANT SELECT ON V_$DATABASE TO C##CDC_PRIVS CONTAINER=ALL;
GRANT SELECT ON V_$INSTANCE to C##CDC_PRIVS CONTAINER=ALL;
GRANT SELECT ON V_$THREAD TO C##CDC_PRIVS CONTAINER=ALL;
GRANT SELECT ON V_$PARAMETER TO C##CDC_PRIVS CONTAINER=ALL;
GRANT SELECT ON V_$NLS_PARAMETERS TO C##CDC_PRIVS CONTAINER=ALL;
GRANT SELECT ON V_$TIMEZONE_NAMES TO C##CDC_PRIVS CONTAINER=ALL;

GRANT SELECT ON DBA_PDBS TO C##CDC_PRIVS CONTAINER=ALL;
GRANT SELECT ON CDB_TABLES TO C##CDC_PRIVS CONTAINER=ALL;
GRANT SELECT ON CDB_TAB_PARTITIONS TO C##CDC_PRIVS CONTAINER=ALL;

ALTER SESSION SET CONTAINER=XEPDB1;
GRANT SELECT ON ordermgmt.products TO C##CDC_PRIVS;
GRANT SELECT ON ordermgmt.regions TO C##CDC_PRIVS;
GRANT SELECT ON ordermgmt.COUNTRIES TO C##CDC_PRIVS;
GRANT SELECT ON ordermgmt.LOCATIONS TO C##CDC_PRIVS;
GRANT SELECT ON ordermgmt.WAREHOUSES TO C##CDC_PRIVS;
GRANT SELECT ON ordermgmt.EMPLOYEES TO C##CDC_PRIVS;
GRANT SELECT ON ordermgmt.PRODUCT_CATEGORIES TO C##CDC_PRIVS;
GRANT SELECT ON ordermgmt.PRODUCTS TO C##CDC_PRIVS;
GRANT SELECT ON ordermgmt.CUSTOMERS TO C##CDC_PRIVS;
GRANT SELECT ON ordermgmt.CONTACTS TO C##CDC_PRIVS;
GRANT SELECT ON ordermgmt.ORDERS TO C##CDC_PRIVS;
GRANT SELECT ON ordermgmt.ORDER_ITEMS TO C##CDC_PRIVS;
GRANT SELECT ON ordermgmt.INVENTORIES TO C##CDC_PRIVS;
GRANT SELECT ON ordermgmt.NOTES TO C##CDC_PRIVS;

ALTER SESSION SET CONTAINER=CDB$ROOT;
GRANT SELECT ON V_$LOG TO C##CDC_PRIVS CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE TO C##CDC_PRIVS CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO C##CDC_PRIVS CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO C##CDC_PRIVS CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO C##CDC_PRIVS CONTAINER=ALL;

GRANT EXECUTE ON SYS.DBMS_LOGMNR TO C##CDC_PRIVS CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_LOGMNR_D TO C##CDC_PRIVS CONTAINER=ALL;


ALTER SESSION SET CONTAINER=XEPDB1;
GRANT FLASHBACK ON ordermgmt.products TO C##CDC_PRIVS;
GRANT FLASHBACK ON ordermgmt.regions TO C##CDC_PRIVS;
GRANT FLASHBACK ON ordermgmt.COUNTRIES TO C##CDC_PRIVS;
GRANT FLASHBACK ON ordermgmt.LOCATIONS TO C##CDC_PRIVS;
GRANT FLASHBACK ON ordermgmt.WAREHOUSES TO C##CDC_PRIVS;
GRANT FLASHBACK ON ordermgmt.EMPLOYEES TO C##CDC_PRIVS;
GRANT FLASHBACK ON ordermgmt.PRODUCT_CATEGORIES TO C##CDC_PRIVS;
GRANT FLASHBACK ON ordermgmt.PRODUCTS TO C##CDC_PRIVS;
GRANT FLASHBACK ON ordermgmt.CUSTOMERS TO C##CDC_PRIVS;
GRANT FLASHBACK ON ordermgmt.CONTACTS TO C##CDC_PRIVS;
GRANT FLASHBACK ON ordermgmt.ORDERS TO C##CDC_PRIVS;
GRANT FLASHBACK ON ordermgmt.ORDER_ITEMS TO C##CDC_PRIVS;
GRANT FLASHBACK ON ordermgmt.INVENTORIES TO C##CDC_PRIVS;
GRANT FLASHBACK ON ordermgmt.NOTES TO C##CDC_PRIVS;

exit;